--Trigger na tabela de usuários (USU_USUARIO),registra as alterações no cadastro
CREATE OR REPLACE TRIGGER LOG_USU
AFTER UPDATE ON USU_USUARIO
FOR EACH ROW
BEGIN
--Se o novo valor do campo for diferente do valor anterior é gerado um log na tabela LOG_USU
IF :OLD.USU_NOME <> :NEW.USU_NOME THEN
INSERT INTO LOG_USU (CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,DT_ALTER,ID_USU_ALT) VALUES ('USU_NOME',:OLD.USU_NOME,:NEW.USU_NOME,:OLD.ID_USU,SYSDATE,:NEW.COD_USU_ALTER);
END IF;

IF :OLD.USU_STATUS <> :NEW.USU_STATUS THEN
INSERT INTO LOG_USU (CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,DT_ALTER,ID_USU_ALT) VALUES ('USU_STATUS',:OLD.USU_STATUS,:NEW.USU_STATUS,:OLD.ID_USU,SYSDATE,:NEW.COD_USU_ALTER);
END IF;

IF :OLD.USU_ADM <> :NEW.USU_ADM THEN
INSERT INTO LOG_USU (CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,DT_ALTER,ID_USU_ALT) VALUES ('USU_ADM',:OLD.USU_ADM,:NEW.USU_ADM,:OLD.ID_USU,SYSDATE,:NEW.COD_USU_ALTER);
END IF;

IF :OLD.ID_GRUPO <> :NEW.ID_GRUPO THEN
INSERT INTO LOG_USU (CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,DT_ALTER,ID_USU_ALT) VALUES ('ID_GRUPO',:OLD.ID_GRUPO,:NEW.ID_GRUPO,:OLD.ID_USU,SYSDATE,:NEW.COD_USU_ALTER);
END IF;

IF :OLD.ID_PARC <> :NEW.ID_PARC THEN
INSERT INTO LOG_USU (CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,DT_ALTER,ID_USU_ALT) VALUES ('ID_PARC',:OLD.ID_PARC,:NEW.ID_PARC,:OLD.ID_USU,SYSDATE,:NEW.COD_USU_ALTER);
END IF;

IF :OLD.USU_ID_VEND <> :NEW.USU_ID_VEND THEN
INSERT INTO LOG_USU (CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,DT_ALTER,ID_USU_ALT) VALUES ('USU_ID_VEND',:OLD.USU_ID_VEND,:NEW.USU_ID_VEND,:OLD.ID_USU,SYSDATE,:NEW.COD_USU_ALTER);
END IF;

IF :OLD.USU_SENHA <> :NEW.USU_SENHA THEN
INSERT INTO LOG_USU (CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,DT_ALTER,ID_USU_ALT) VALUES ('USU_SENHA','????','????',:OLD.ID_USU,SYSDATE,:NEW.COD_USU_ALTER);
END IF;


END;
